# Sets the relation of branches in current repository with
# source repositories branches

staging_fork:
- repo: davidcassany/elemental-toolkit
  branch: bump_libraries_2.3
  parseVersion: patch
  versionOffset: no
- repo: davidcassany/elemental-operator
  branch: bump_libraries_1.9
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-operator
  branch: v1.8.x
  parseVersion: patch
  versionOffset: no
- repo: davidcassany/elemental-os
  branch: update_kvm_flavor
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-channels
  branch: v1.8
  parseVersion: none
  versionOffset: no

maintenance_6.2_fork:
- repo: davidcassany/elemental-toolkit
  branch: bump_libraries_2.3
  parseVersion: patch
  versionOffset: no
- repo: davidcassany/elemental-operator
  branch: bump_libraries_1.8
  parseVersion: patch
  versionOffset: no
- repo: davidcassany/elemental
  branch: update_kvm_flavor
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-channels
  branch: v1.8
  parseVersion: none
  versionOffset: no

maintenance_6.1:
- repo: rancher/elemental-toolkit
  branch: v2.2.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-operator
  branch: v1.7.x
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental
  branch: v2.2.x
  parseVersion: patch
  versionOffset: no
- repo: rancher-sandbox/cluster-api-provider-elemental
  branch: main
  parseVersion: patch
  versionOffset: no
- repo: rancher/elemental-channels
  branch: v1.7
  parseVersion: none
  versionOffset: no
