# Sets the relation of branches in current repository with
# source repositories branches

dev:
- repo: davidcassany/elemental-toolkit
  branch: testing_obsgit
- repo: davidcassany/elemental-operator
  branch: testing_obsgit
- repo: davidcassany/elemental
  branch: testing_obsgit
