name: Verify scripts with Shellcheck

on:
  pull_request:
    branches:
    - main

jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Shellcheck
      run: |
        set -x
        
        [ ! -d scripts ] && exit 1

        shellcheck scripts/common.sh
        shellcheck scripts/prepare-sources.sh
        shellcheck scripts/update-sources.sh
