name: Update OBS sources

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch to upgrade in OBS'
        required: true
        default: 'dev'
  schedule:
  - cron: "0 */2 * * *"

concurrency:
  group: soucre-update-${{ inputs.target_branch }}

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  update-sources:
    env:
      BRANCH: ${{ inputs.target_branch || 'dev' }} 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout builders
      run: |
        set -x
        
        [ -d builders ] && exit 1
        [ -f Makefile ] && exit 1

        git fetch origin +${{ github.ref_name }}:${{ github.ref_name }}
        git checkout ${{ github.ref_name }} -- scripts Makefile config.yaml
    - name: Run prepare-sources
      run: |
        count=$(yq ".${{ env.BRANCH }} | length" config.yaml)

        for ((n=0;n<${count};n++)); do
          export REPO="$(yq ".${{ env.BRANCH }}.[${n}].repo" config.yaml)"
          export BRANCH="$(yq ".${{ env.BRANCH }}.[${n}].branch" config.yaml)"
          export V_PARSE="$(yq ".${{ env.BRANCH }}.[${n}].parseVersion" config.yaml)"
          export V_OFFSET="$(yq ".${{ env.BRANCH }}.[${n}].versionOffset" config.yaml)"

          make prepare-sources
        done
    - name: Update sources
      run: |
        make update-sources 
    - name: Clean paths
      run: |
        rm -rf scripts
        rm -f Makefile config.yaml
    - name: Checkout new branch ${{ env.BRANCH }}_stage
      id: commit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # TODO set an OBS user as this might be used for *.changes generation
        git config --global user.email "do-not-use@elemental.suse.com"
        git config --global user.name "GitHub Action Runner"

        git checkout -b ${{ env.BRANCH }}_stage
        git add .

        if [ -z "$(git status --porcelain)" ]; then
          echo "Clean work tree, nothing to do"
          echo "clean=true" >> "${GITHUB_OUTPUT}"
          exit 0
        else
          echo "clean=false" >> "${GITHUB_OUTPUT}"
        fi

        git commit -s -m "Automated commit from GHA workflow"
        git push origin ${{ env.BRANCH }}_stage --force
    - if: ${{ steps.commit.outputs.clean != 'true' }} 
      name: Update/create PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        json=$(gh pr list --repo ${{ github.repository }} --json number,baseRefName,headRefName --head ${{ env.BRANCH }}_stage --base ${{ env.BRANCH }} --limit 1)

        if [ "$(echo "${json}" | jq length)" -eq 1 ]; then
          number="$(echo "${json}" | jq '.[0].number')"
          gh pr comment "${number}" --repo ${{ github.repository }} --body "Updating PR from sources"
        else
          gh pr create --repo ${{ github.repository }} --head ${{ env.BRANCH }}_stage --base ${{ env.BRANCH }} \
            --body "Automated PR from GH client" --title "Update '${{ env.BRANCH }}' OBS sources"
        fi
